import { FormGroup } from "@/components/FormGroup";
import { Button } from "@/components/button";
import Input from "@/components/input";
import { useBuyCredits } from "@/hooks/useBuyCredits";
import { api } from "@/utils/api";
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
// import { api } from "@/utils/api";

const GeneratePage: NextPage = () => {
  const { buyCredits } = useBuyCredits();

  const [form, setForm] = useState({
    prompt: "",
  });
  const [imageUrl, setImageUrl] = useState("");

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data) {
      console.log("mutation finished", data.imageUrl);
      if (!data.imageUrl) return;
      setImageUrl(data.imageUrl);
    },
  });

  function handleFormSubmit(e: React.FormEvent) {
    e.preventDefault();
    generateIcon.mutate({
      prompt: form.prompt,
    });
    setForm({ prompt: "" });
  }

  function updateForm(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value,
      }));
    };
  }

  const session = useSession();

  const isLoggedIn = !!session.data;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-zinc-950 ">
        {!isLoggedIn && <></>}
        {isLoggedIn && (
          <>
            {/* <Button
              onClick={() => {
                buyCredits().catch(console.error);
              }}
            >
              Buy Credits
            </Button> */}
          </>
        )}

        <form onSubmit={handleFormSubmit} className="flex flex-col gap-4">
          <FormGroup>
            <label className="font-semibold">Prompt</label>
            <Input value={form.prompt} onChange={updateForm("prompt")}></Input>
          </FormGroup>
          <Button>Submit</Button>
        </form>
        <Image
          src={imageUrl}
          width={100}
          height={100}
          alt="image generated from the app"
        />
      </main>
    </>
  );
};

export default GeneratePage;
