import { FormGroup } from "@/components/FormGroup";
import Input from "@/components/input";
import { api } from "@/utils/api";
import { type NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
  });

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data) {
      console.log("mutation finished", data);
    },
  });

  function handleFormSubmit(e: React.FormEvent) {
    e.preventDefault();
    // TODO: Submit the form data to the backend.
    generateIcon.mutate({
      prompt: form.prompt,
    });
  }

  function updateForm(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value,
      }));
    };
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-neutral-700 to-neutral-950 ">
        <form onSubmit={handleFormSubmit} className="flex flex-col gap-4">
          <FormGroup>
            <label className="font-semibold">Prompt</label>
            <Input value={form.prompt} onChange={updateForm("prompt")}></Input>
          </FormGroup>
          <button id="submit-btn">Submit</button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;
